### ISSUE TITLE
Axis/Belt/Vibrations calibration not working after clean install.

### ISSUE THREAD

**Issue by Ekodas** [Frix-x/klippain#379]
### Klippain branch

- [X] I confirm using the main branch

### Version

v4.2.0-11-g822f3bc2

### Describe the bug and expected behavior

After a clean install of RasPi lite OS, Klipper, Mainsail, and Klippain, none of the accelerometer calibration scripts will produce the appropriate graphs.  OS was installed through Rasperry Pi Imager.  Klipper, Mainsail, and Moonraker installed through KIAUH.  Klippain installed and configured as directed at https://github.com/Frix-x/klippain.  Numpy and libraries installed as directed at https://www.klipper3d.org/Measuring_Resonances.html.  Using built in ADXL345 on EBB36 v1.2.  

### Additional information and klippy.log

After completion of test, I receive the following messages in the console:

9:54 PM
Command {plot_graph} finished
9:54 PM
ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.
9:54 PM
array = np.asarray(DummyArray(interface, base=x))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
9:54 PM
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/numpy/lib/stride_tricks.py", line 105, in as_strided
9:54 PM
return as_strided(x, strides=out_strides, shape=out_shape,
9:54 PM
File "/usr/lib/python3/dist-packages/numpy/lib/stride_tricks.py", line 336, in sliding_window_view
9:54 PM
return np.lib.stride_tricks.sliding_window_view(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<__array_function__ internals>", line 200, in sliding_window_view
9:54 PM
File "/usr/lib/python3/dist-packages/matplotlib/mlab.py", line 258, in _stride_windows
9:54 PM
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
9:54 PM
result = _stride_windows(x, NFFT, noverlap)
9:54 PM
File "/usr/lib/python3/dist-packages/matplotlib/mlab.py", line 382, in _spectral_helper
9:54 PM
spec, freqs, t = _spectral_helper(x=x, y=None, NFFT=NFFT, Fs=Fs,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
9:54 PM
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/pi/klippain_config/scripts/is_workflow/graph_belts.py", line 298, in combined_spectrogram
pdata1, bins1, t1 = compute_spectrogram(data1)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/pi/klippain_config/scripts/is_workflow/graph_belts.py", line 185, in compute_spectrogram
pdata, bins, t = _specgram(d['x'])
^^^^^^^^^^^^^^^^^
File "/home/pi/klippain_config/scripts/is_workflow/graph_belts.py", line 180, in _specgram
return matplotlib.mlab.specgram(
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/matplotlib/mlab.py", line 780, in specgram
9:54 PM
combined_data, bins, t = combined_spectrogram(data1, data2)
9:54 PM
plot_difference_spectrogram(ax2, datas[0], datas[1], signal1, signal2, similarity_factor, max_freq)
File "/home/pi/klippain_config/scripts/is_workflow/graph_belts.py", line 467, in plot_difference_spectrogram
9:54 PM
fig = belts_calibration(lognames, KLIPPER_FOLDER)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/pi/klippain_config/scripts/is_workflow/graph_belts.py", line 603, in belts_calibration
9:54 PM
fig, png_filename = get_belts_graph()
^^^^^^^^^^^^^^^^^
File "/home/pi/printer_data/config/scripts/is_workflow/is_workflow.py", line 89, in get_belts_graph
9:54 PM
main()
File "/home/pi/printer_data/config/scripts/is_workflow/is_workflow.py", line 215, in main
9:54 PM
Belts estimated similarity: 94.2%
Traceback (most recent call last):
File "/home/pi/printer_data/config/scripts/is_workflow/is_workflow.py", line 231, in
9:54 PM
Running Command {plot_graph}...:
9:54 PM
echo: Belts graphs generation...
9:54 PM
Writing raw accelerometer data to /tmp/raw_data_axis=1.000,-1.000_a.csv file

[klippy (4).log](https://github.com/Frix-x/klippain/files/13595485/klippy.4.log)

**Comment by Frix-x** [comment]
Thanks for raising an issue. I'll close this one in favor of the one in Shake&Tune module.
I've got a plan to solve it but just need some time ^^

In the meantime, switching to a 64 bit OS always solve the issue apparently (but 32 bit OS is not the only cause since some people are able to run it on this kind of system)
