### ISSUE TITLE
Upgrade to the latest Klippain Bug? 

### ISSUE THREAD

**Issue by M3HNGRY** [Frix-x/klippain#509]
### Klippain branch

- [X] I confirm using the main branch

### Version

v4.3.0-0-geeb49160

### Describe the bug and expected behavior

Updated to the latest Klippain. Octopus, Tap, SB2240, BTT USB2CAN, and Pi4.  Able to input shape x and y now. When I go to print. 

1. Unknown gcode_macro_variable "adaptive_primeline" 
2. No extruder retraction because extruder temp is (48.88) is lower then min_extrude_temp (172)
3. SDCARD_RESET_FILE cannot be run from the sdcard
```
`SDCARD_RESET_FILE cannot be run from the sdcard
virtual_sdcard on_error
Traceback (most recent call last):
  File "/home/mainsail/klipper/klippy/extras/virtual_sdcard.py", line 264, in work_handler
    self.gcode.run_script(line)
  File "/home/mainsail/klipper/klippy/gcode.py", line 229, in run_script
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/mainsail/klipper/klippy/gcode.py", line 211, in _process_commands
    handler(gcmd)
  File "/home/mainsail/klipper/klippy/gcode.py", line 137, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
  File "/home/mainsail/klipper/klippy/extras/gcode_macro.py", line 189, in cmd
    self.template.run_gcode_from_command(kwparams)
  File "/home/mainsail/klipper/klippy/extras/gcode_macro.py", line 68, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
  File "/home/mainsail/klipper/klippy/gcode.py", line 226, in run_script_from_command
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/mainsail/klipper/klippy/gcode.py", line 211, in _process_commands
    handler(gcmd)
  File "/home/mainsail/klipper/klippy/gcode.py", line 137, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
  File "/home/mainsail/klipper/klippy/gcode.py", line 147, in <lambda>
    handler = lambda gcmd: self._cmd_mux(cmd, gcmd)
  File "/home/mainsail/klipper/klippy/gcode.py", line 315, in _cmd_mux
    values[key_param](gcmd)
  File "/home/mainsail/klipper/klippy/extras/gcode_macro.py", line 170, in cmd_SET_GCODE_VARIABLE
    raise gcmd.error("Unknown gcode_macro variable '%s'" % (variable,))
gcode.CommandError: Unknown gcode_macro variable 'adaptive_primeline'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mainsail/klipper/klippy/extras/virtual_sdcard.py", line 268, in work_handler
    self.gcode.run_script(self.on_error_gcode.render())
  File "/home/mainsail/klipper/klippy/gcode.py", line 229, in run_script
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/mainsail/klipper/klippy/gcode.py", line 211, in _process_commands
    handler(gcmd)
  File "/home/mainsail/klipper/klippy/gcode.py", line 137, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
  File "/home/mainsail/klipper/klippy/extras/gcode_macro.py", line 189, in cmd
    self.template.run_gcode_from_command(kwparams)
  File "/home/mainsail/klipper/klippy/extras/gcode_macro.py", line 68, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
  File "/home/mainsail/klipper/klippy/gcode.py", line 226, in run_script_from_command
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/mainsail/klipper/klippy/gcode.py", line 211, in _process_commands
    handler(gcmd)
  File "/home/mainsail/klipper/klippy/gcode.py", line 137, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
  File "/home/mainsail/klipper/klippy/extras/virtual_sdcard.py", line 138, in cmd_SDCARD_RESET_FILE
    raise gcmd.error(
gcode.CommandError: SDCARD_RESET_FILE cannot be run from the sdcard`
```
4. Neopixel update did not succeed - Error

This what my console shows. 

![Error](https://github.com/Frix-x/klippain/assets/131578650/fa692ff3-1f6c-431c-a09f-c1b3f8672339)

My Orca slicer start gcode. 

START_PRINT EXTRUDER_TEMP=[nozzle_temperature_initial_layer] BED_TEMP=[bed_temperature_initial_layer_single] MATERIAL=[filament_type] CHAMBER=[chamber_temperature] SIZE={first_layer_print_min[0]}_{first_layer_print_min[1]}_{first_layer_print_max[0]}_{first_layer_print_max[1]} TOTAL_LAYER=[total_layer_count]

end gcode

END_PRINT

layer change gcode

SET_PRINT_STATS_INFO CURRENT_LAYER={layer_num}

### Additional information and klippy.log

[moonraker (1).log](https://github.com/Frix-x/klippain/files/14427814/moonraker.1.log)
[klippy (14).log](https://github.com/Frix-x/klippain/files/14429054/klippy.14.log)

**Comment by joseaneuro** [comment]
I'm also having the same issue. I looked in the prime_line.cfg file and can't find a reference to ADAPTIVE_PRIMELINE. I'm wondering if the PRIMELINE macro was supposed to be renamed to ADAPTIVE_PRIMELINE.

**Comment by M3HNGRY** [comment]
The other klippy log was empty. Here is current one. 

[klippy (14).log](https://github.com/Frix-x/klippain/files/14429054/klippy.14.log)

**Comment by joseaneuro** [comment]
@Frix-x Found the fix!

The START_PRINT macro was missing "variable_adaptive_primeline: 1" inside it. Redifining it in the overrides to add that fixes it.

![image](https://github.com/Frix-x/klippain/assets/95442514/02bbeb37-0a37-4872-9be7-bd5e07f5a008)

**Comment by Frix-x** [comment]
Adaptive prime line variable was indeed added a couple of hours ago. I still need to fix the rest. Thanks for raising this issue :)

**Comment by Frix-x** [comment]
Everything should be fixed except the Neopixel part. Do you have more info about the problem?

**Comment by M3HNGRY** [comment]
Frix, 

I have updated and now printing. I think we are good to go now. I will keep an eye on the neopixel part and open a new ticket if there is any more errors. . Thanks!

**Comment by Frix-x** [comment]
Thanks! I'll close this issue then :)
